### ISSUE TITLE
Error when try gulp set

### ISSUE THREAD

**Issue by enmachs** [enmachs/front-env#39]
Error trace:
```
➜  front-env git:(remove-neat/32) ✗ gulp set
[23:21:12] Using gulpfile /media/enmachs/Backup/EnmaChs/Lab/front-env/gulpfile.js
[23:21:12] Starting 'set'...
[23:21:12] Starting 'clean:dist'...
[23:21:12] Finished 'clean:dist' after 1.8 ms
[23:21:12] Starting 'add_jquery'...
[23:21:12] Finished 'add_jquery' after 63 ms
[23:21:12] Starting 'compile_slim'...
[23:21:12] Starting 'compile_sass'...
[23:21:12] Starting 'images'...
[23:21:12] Starting 'fonts'...
[23:21:12] Starting 'css'...
[23:21:12] Starting 'js'...
[23:21:12] gulp-imagemin: Minified 0 images
[23:21:12] Finished 'images' after 9.03 ms
[23:21:12] Finished 'fonts' after 8.22 ms
[23:21:12] Finished 'css' after 8.93 ms
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:78:25)
    at writeGeneric (internal/stream_base_commons.js:73:3)
    at Socket._writeGeneric (net.js:714:5)
    at Socket._write (net.js:726:8)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Socket.Writable.write (_stream_writable.js:299:11)
    at DestroyableTransform._transform (/media/enmachs/Backup/EnmaChs/Lab/front-env/node_modules/gulp-slim/index.js:127:28)
    at DestroyableTransform.Transform._read (/media/enmachs/Backup/EnmaChs/Lab/front-env/node_modules/gulp-slim/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/media/enmachs/Backup/EnmaChs/Lab/front-env/node_modules/gulp-slim/node_modules/readable-stream/lib/_stream_transform.js:172:12)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:430:5)
    at onwrite (_stream_writable.js:461:5)
    at _destroy (internal/streams/destroy.js:49:7)
    at Socket._destroy (net.js:614:3)
    at Socket.destroy (internal/streams/destroy.js:37:8)
    at afterWriteDispatched (internal/stream_base_commons.js:78:17)
    at writeGeneric (internal/stream_base_commons.js:73:3)
    at Socket._writeGeneric (net.js:714:5)
    at Socket._write (net.js:726:8)
```
`$ node -v` -> `v10.20.1`

**Comment by enmachs** [comment]
Solved: Same from #40
