### ISSUE TITLE
Error when gulp set

### ISSUE THREAD

**Issue by enmachs** [enmachs/front-env#40]
Error trace:
```
➜  front-env git:(remove-neat/32) ✗ gulp set
[23:29:08] Using gulpfile /media/enmachs/Backup/EnmaChs/Lab/front-env/gulpfile.js
[23:29:08] Starting 'set'...
[23:29:08] Starting 'clean:dist'...
[23:29:08] Finished 'clean:dist' after 2.15 ms
[23:29:08] Starting 'add_jquery'...
[23:29:08] Finished 'add_jquery' after 39 ms
[23:29:08] Starting 'compile_slim'...
[23:29:08] Starting 'compile_sass'...
[23:29:08] Starting 'images'...
[23:29:08] Starting 'fonts'...
[23:29:08] Starting 'css'...
[23:29:08] Starting 'js'...
[23:29:08] gulp-imagemin: Minified 0 images
[23:29:08] Finished 'images' after 11 ms
[23:29:08] Finished 'fonts' after 9.14 ms
[23:29:08] Finished 'css' after 9.87 ms
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn slimrb ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
`$ node -v` -> `v10.13.0`

**Comment by enmachs** [comment]
Solved: Running `gem install slim`
